server:
  port: 9992
spring:
  application:
    name: JOB-COMPANY
#    服务注册地址
  cloud:
    nacos:
      server-addr: 192.168.207.129:8848
#    数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.207.129:3306/job_incon?characterEncoding=UTF-8
    username: root
    password: 111111
#     redis
  redis:
    host: 192.168.207.129
    port: 7000
    database: 0
#    日志
logging:
  level:
    com.wly.dao: debug
#    配置mybatis
mybatis:
  mapper-locations: classpath:com/wly/mapper/*.xml


#设置openfeign调用超时
feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
# rabbitmq
  rabbitmq:
    host: 192.168.207.129
    port: 5672
    username: root
    password: 111111
    virtual-host: /